/*
Deployment script for C:\USERS\SAIMON\DOWNLOADS\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\SAIMON\DOWNLOADS\DATABASE.MDF"
:setvar DefaultFilePrefix "C_\USERS\SAIMON\DOWNLOADS\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\Saimon\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Saimon\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
/*
The type for column CityId in table [dbo].[City] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.
*/
GO
PRINT N'Starting rebuilding table [dbo].[City]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_City] (
    [CityId]   INT    identity     NOT NULL,
    [CityName] NVARCHAR (200) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_City] PRIMARY KEY CLUSTERED ([CityId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[City])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_City] ( [CityName])
        SELECT   
                 [CityName]
        FROM     [dbo].[City]
        ORDER BY [CityId] ASC;
    END

DROP TABLE [dbo].[City];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_City]', N'City';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_City]', N'PK_City', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[City].[UQ__City__0000000000000066]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__City__0000000000000066]
    ON [dbo].[City]([CityId] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The type for column ClassificationId in table [dbo].[Classification] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Classification]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Classification] (
    [ClassificationId]   INT      identity   NOT NULL,
    [ClassificationName] NVARCHAR (100) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Classification] PRIMARY KEY CLUSTERED ([ClassificationId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Classification])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Classification] ([ClassificationName])
        SELECT   
                 [ClassificationName]
        FROM     [dbo].[Classification]
        ORDER BY [ClassificationId] ASC;
    END

DROP TABLE [dbo].[Classification];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Classification]', N'Classification';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Classification]', N'PK_Classification', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Classification].[UQ__Classification__0000000000000074]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__Classification__0000000000000074]
    ON [dbo].[Classification]([ClassificationId] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The type for column ClassificationId in table [dbo].[Client] is currently  UNIQUEIDENTIFIER NULL but is being changed to  INT NULL. There is no implicit or explicit conversion.

The type for column ClientId in table [dbo].[Client] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.

The type for column RegionId in table [dbo].[Client] is currently  UNIQUEIDENTIFIER NULL but is being changed to  INT NULL. There is no implicit or explicit conversion.

The type for column SellerId in table [dbo].[Client] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.
*/
PRINT N'Starting rebuilding table [dbo].[Client]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Client] (
    [Name]             NVARCHAR (200) NOT NULL,
    [Phone]            NVARCHAR (100) NOT NULL,
    [Gender]           NVARCHAR (1)   NULL,
    [LastPurchase]     DATETIME       NULL,
    [SellerId]         INT            NOT NULL,
    [RegionId]         INT            NULL,
    [ClassificationId] INT            NULL,
    [ClientId]         INT     identity    NOT NULL,
    [Address]          NVARCHAR (255) NULL,
    [Occupation]       NVARCHAR (100) NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK__Client__00000000000000CA] PRIMARY KEY CLUSTERED ([ClientId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Client])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Client] ( [Name], [Phone], [Gender], [LastPurchase], [SellerId], [RegionId], [ClassificationId], [Address], [Occupation])
        SELECT   
                 [Name],
                 [Phone],
                 [Gender],
                 [LastPurchase],
                 1,
                 1,
                 1,
                 [Address],
                 [Occupation]
        FROM     [dbo].[Client]
        ORDER BY [ClientId] ASC;
    END

DROP TABLE [dbo].[Client];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Client]', N'Client';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK__Client__00000000000000CA]', N'PK__Client__00000000000000CA', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Client].[UQ__Client__00000000000000C2]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__Client__00000000000000C2]
    ON [dbo].[Client]([ClientId] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The type for column CityId in table [dbo].[Region] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.

The type for column RegionId in table [dbo].[Region] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Region]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Region] (
    [RegionId]   INT        identity    NOT NULL,
    [RegionName] NVARCHAR (200) NOT NULL,
    [CityId]     INT            NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Region] PRIMARY KEY CLUSTERED ([RegionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Region])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Region] ( [RegionName], [CityId])
        SELECT   
                 [RegionName],
                 1
        FROM     [dbo].[Region]
        ORDER BY [RegionId] ASC;
    END

DROP TABLE [dbo].[Region];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Region]', N'Region';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Region]', N'PK_Region', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Region].[UQ__Region__000000000000003D]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__Region__000000000000003D]
    ON [dbo].[Region]([RegionId] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The type for column UserId in table [dbo].[User] is currently  UNIQUEIDENTIFIER NOT NULL but is being changed to  INT NOT NULL. There is no implicit or explicit conversion.
*/
GO
PRINT N'Starting rebuilding table [dbo].[User]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_User] (
    [Email]    NVARCHAR (100) NOT NULL,
    [Name]     NVARCHAR (200) NOT NULL,
    [UserId]   INT          identity  NOT NULL,
    [Password] NVARCHAR (255) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK__User__00000000000000AF] PRIMARY KEY CLUSTERED ([UserId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[User])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_User] ([Email], [Name], [Password])
        SELECT   
                 [Email],
                 [Name],
                 [Password]
        FROM     [dbo].[User]
        ORDER BY [UserId] ASC;
    END

DROP TABLE [dbo].[User];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_User]', N'User';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK__User__00000000000000AF]', N'PK__User__00000000000000AF', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

GO


PRINT N'Creating [dbo].[User].[UQ__User__0000000000000013]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__User__0000000000000013]
    ON [dbo].[User]([Email] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[User].[UQ__User__00000000000000A7]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__User__00000000000000A7]
    ON [dbo].[User]([UserId] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Classification_Client]...';


GO
ALTER TABLE [dbo].[Client] WITH NOCHECK
    ADD CONSTRAINT [FK_Classification_Client] FOREIGN KEY ([ClassificationId]) REFERENCES [dbo].[Classification] ([ClassificationId]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Region_Client]...';


GO
ALTER TABLE [dbo].[Client] WITH NOCHECK
    ADD CONSTRAINT [FK_Region_Client] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Region] ([RegionId]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_User_Client]...';


GO
ALTER TABLE [dbo].[Client] WITH NOCHECK
    ADD CONSTRAINT [FK_User_Client] FOREIGN KEY ([SellerId]) REFERENCES [dbo].[User] ([UserId]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_City_Region]...';


GO
ALTER TABLE [dbo].[Region] WITH NOCHECK
    ADD CONSTRAINT [FK_City_Region] FOREIGN KEY ([CityId]) REFERENCES [dbo].[City] ([CityId]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Client] WITH CHECK CHECK CONSTRAINT [FK_Classification_Client];

ALTER TABLE [dbo].[Client] WITH CHECK CHECK CONSTRAINT [FK_Region_Client];

ALTER TABLE [dbo].[Client] WITH CHECK CHECK CONSTRAINT [FK_User_Client];

ALTER TABLE [dbo].[Region] WITH CHECK CHECK CONSTRAINT [FK_City_Region];


GO
PRINT N'Update complete.';


GO
